### ISSUE TITLE
По ссылке на GH Pages отображается readme файл, а не сайт

### ISSUE THREAD

**Issue by zerjg** [SolovyevaMaria/web#2]
Необходимо главную страницу переименовать в index.html и исправить ссылки на неё с других страниц.
https://solovyevamaria.github.io/web/

**Comment by SolovyevaMaria** [comment]
> Необходимо главную страницу переименовать в index.html и исправить ссылки на неё с других страниц. https://solovyevamaria.github.io/web/

Переименовано
